### ISSUE TITLE
App Service in Azure works fine until monday morning and then, Unable to find an entry point named 'CreateServiceProvider' in DLL 'Microsoft.Azure.Documents.ServiceInterop.dll'

### ISSUE THREAD

**Issue by AnQueth** [Azure/azure-cosmosdb-dotnet#575]
So the app services were running fine friday.
monday morning we had Unable to find an entry point named 'CreateServiceProvider' in DLL 'Microsoft.Azure.Documents.ServiceInterop.dll'
restarting the app service fixes the problem. 
I have a memory dump of the process.
What would be the cause here?

**Comment by ealsur** [comment]
This is due to the Interop DLL being blocked by some process. It could've been a deployment or an underlying update on the App Service.

Restarting the App Service releases the locked DLL and let's your application access it.
