### ISSUE TITLE
MongoDB API support for MongoDB 4.0 multi-document transactions

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-cosmosdb-dotnet#593]
With MongoDB adding support for [multi-document transactions](https://docs.mongodb.com/manual/core/transactions/) in API version 4.0 and official [supported by .NET Driver 2.7](https://mongodb.github.io/mongo-csharp-driver/2.7/what_is_new/), would be nice to see that support coming to CosmosDB MongoDB API.

**Comment by ealsur** [comment]
Hi @SeanFeldman, Cosmos DB Mongo API supports commands up to v3.2/v3.4. To request new features please use the [Cosmos DB UserVoice site](https://feedback.azure.com/forums/263030-azure-cosmos-db).

Thanks!

**Comment by SeanFeldman** [comment]
There's already a [request](https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/35324563-support-for-transactions-via-mongo-4-0-api). Too bad 2 systems are used to manage requests.
