### ISSUE TITLE
Nuget Package DLL is not optimized ?

### ISSUE THREAD

**Issue by cdie** [Azure/azure-cosmosdb-dotnet#594]
Hello,

When trying to run a benchmark of my system targeting CosmosDb (with BenchmarkDotNet), I have a warning that states:

Assembly CQELight_Benchmarks which defines benchmarks references non-optimized Microsoft.Azure.DocumentDB.Core

Is this the expected behavior ?

**Comment by ealsur** [comment]
@cdie Could you share which SDK / Nuget version are you using?

**Comment by cdie** [comment]
@ealsur Sure, I'm using Microsoft.Azure.DocumentDB.Core v2.0.0, in a netcoreapp2.1

**Comment by ealsur** [comment]
Are you blocked by this BenchmarkDotNet warning? Are you running your Benchmarks in Any CPU, x64 or x86?

**Comment by cdie** [comment]
In fact, this is not a blocking issue for me, I run my benchmarks with this version just fine. 
However, I'm not 100% confident that, with not optimized dlls, I can have same results than using optimized ones.
This issue is mainly to let your team know this and see if this is expected or just something you forget

**Comment by ealsur** [comment]
Nuget DLLs are compiled on Release, I wonder why BenchmarkDotNet says it's not optimized. I'll check in BenchmarkDotNet's docs and see if there is any explanation to the verification they do.

**Comment by cdie** [comment]
You double check that "Optimize code" checkbox is checked on your release configuration ?

**Comment by ealsur** [comment]
Nuget DLLs are shipped through release pipelines, we'll investigate if the release pipeline is setting the `<Optimize>` attribute correctly.

**Comment by ealsur** [comment]
@cdie It seems this is affecting only the "Core" package version, not the Full Framework one. I'm investigating and will share results today.

**Comment by ealsur** [comment]
2.1.0 has been released with the optimizations enabled.
