### ISSUE TITLE
Namespace Azure does not exist in Microsoft

### ISSUE THREAD

**Issue by ryancole** [Azure/azure-cosmosdb-dotnet#596]
Hi folks,

I've got a netstandard2.0 project into which I've installed `Microsoft.Azure.DocumentDB` version `2.0` package into. I've copied over some code from an older version of the documentdb library. My `using` statements no longer seem to work, but I can see nowhere saying that this was changed. The samples still use this namespace, etc.

Any clue why I'm unable to use this library?

![untitled](https://user-images.githubusercontent.com/484801/45728709-d8b08f80-bb8e-11e8-8aab-48db5b164939.png)

**Comment by ealsur** [comment]
If you are working on NET Standard / NET Core, please use the [Microsoft.Azure.DocumentDB.Core package](https://www.nuget.org/packages/Microsoft.Azure.DocumentDB.Core/).

**Comment by TomasHubelbauer** [comment]
This could _really really_ use a note in the README.

**Comment by ealsur** [comment]
@TomasHubelbauer On the official documetation, NET and NET Core have separate articles, both pointing to their NuGets:
* https://docs.microsoft.com/azure/cosmos-db/sql-api-sdk-dotnet
* https://docs.microsoft.com/azure/cosmos-db/sql-api-sdk-dotnet-core

**Comment by TomasHubelbauer** [comment]
Yes, indeed, and it's so easy to miss, too, when you're reading the wrong one, hence my comment 🙂 I sunk a good half and hour into just that today. Should I have noticed? Yeah. Did I? No. Am I alone in this? 🤷‍♂️

**Comment by ealsur** [comment]
Totally true! Just to weight where would be a better place. Did you land in Github first or did you hit the NET docs? Just to know whether a README or a note on the NET docs should be better.

**Comment by TomasHubelbauer** [comment]
The .NET docs I think, 90 %, that's where I landed from Google and I submitted a PR there adding a note to the .NET non-Core doc with a link to the .NET Core one (maybe we should do the other way as well?). README IMO should have at least a mention too, I went there when trying to find more info before I found this issue.
