### ISSUE TITLE
Upsert does not populate Cosmos DB Change Feed

### ISSUE THREAD

**Issue by birynk** [Azure/azure-cosmosdb-dotnet#597]
In our tests, insert and replace trigger a Cosmos DB Change Feed but an UPSERT not. Is this an intended/accepted behaviour?

And if yes would be great if it is documented.

I am using Microsoft.Azure.DocumentDB.ChangeFeedProcessor, version 2.1.0 in a ASP.Net Core 2.1.

**Comment by ealsur** [comment]
@birynk Upsert does work and you should be seeing it in the Change Feed Library. I just did a test project using the Change Feed Processor library and I can see the library picking up Upserts without issues.

Here is a [standalone repo](https://github.com/ealsur/changefeedsample) with a project using the Change Feed Processor that will:
* Create a monitored collection and leases collection
* Start an Observer
* Upsert documents in the background

**Comment by birynk** [comment]
Thank you for the fast response. I've run the sample you have send and indeed it is working.

In our tests we were doing upserts with Etag check and the FeedObserver was not always picking the latest version of the upserted document. Unfortunatelly, this is a behaviour that I cannot always reproduce.  

Maybe there is something special with our configuration.  
We are starting two FeedObservers for two different collections and both of them are using the same Lease collection.  The host name is different with every run. Moreover none of the collections have partitions.

**Comment by ealsur** [comment]
@birynk Do your FeedObservers do different things? If so, you need to assign a different `LeasePrefix` to each if you want to share the Lease Collection.

**Comment by birynk** [comment]
Indeed the issue was with the Leases Collection. Adding the Prefix made it to behave deterministic.  I thought that having different monitored collections it would not matter.

Both upserts with _etag and without _etag were behaving underterministic.  When I run your sample with etag check and without I always got the expected notification. 

So it was a problem with our configuration. Thank you for the tip.
