### ISSUE TITLE
Cosmos DB Windows emulator needs restart after machine has hibernated for a longer period

### ISSUE THREAD

**Issue by mronnlun** [Azure/azure-cosmosdb-dotnet#599]
Start the Windows emulator (1.22.0.0)
The management web page opens (https://localhost:8081/_explorer/index.html)
Select Explorer in the web page menu and check databases and collections
Hibernate the machine (over night)
Resume from hibernation
Try to open Explorer menu in webpage -> I just keeps loading

Refreshing the web page works and Quickstart page will be shown but moving to Explorer page will just show a loading page.

**Comment by ealsur** [comment]
This is covered in the [Troubleshooting section in the Emulator docs](https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator#troubleshooting).

> While the Emulator is running, if your computer goes to sleep mode or runs any OS updates, you might see a Service is currently unavailable message. Reset the Emulator, by right clicking on the icon that appears on the windows notification tray and select Reset Data.

**Comment by ealsur** [comment]
This is a known and documented behavior regarding computer hibernation.
