### ISSUE TITLE
Update nuget dependency on System.Net.Security to > 4.0.0

### ISSUE THREAD

**Issue by brendankowitz** [Azure/azure-cosmosdb-dotnet#610]
**Describe the bug**
The CosmosDB Core client SDK depends on an insecure version of System.Net.Security (4.0.0). This gives downstream code the vulnerability documented here (https://github.com/aspnet/Announcements/issues/239). Please update to a secure version by default.

**Expected behavior**
Using CosmosDB Core client SDK **does not** introduce dependencies with known vulnerabilities

**Actual behavior**
Using CosmosDB Core client SDK **introduces** a dependency with a known vulnerability

**Comment by jackbond** [comment]
Thank you so much for bringing this to our attention. We at Microsoft take security very seriously and sincerely apologize for not being aware of this issue. We assure you that we will be testing and releasing a fix ASAP.

Only one problem...

I don't work for Microsoft or the CosmosDb team. If I did, the incompetent hacks managing this team would have been fired ages ago. Seriously, how many EFFING times are the clowns responsible for the .net SDK going to be allowed to EFF up before something is done?

And please, spare me the open source code of conduct BS. This is the official Microsoft support forum for a BILLION dollar product. The buck has to end somewhere, and where it currently ends is a joke.

**Comment by kirillg** [comment]
it's indeed a known issue, and the fix is being released shortly.

Your grotesquely incompetent fan of Jack Bond :) . Jack, we love you, keep it coming.

**Comment by kirillg** [comment]
this was released on MOnday, resolving
