### ISSUE TITLE
Exposing the partition key range id cache?

### ISSUE THREAD

**Issue by Elfocrash** [Azure/azure-cosmosdb-dotnet#613]
**Is your feature request related to a problem? Please describe.**
We are currently unable to run cross partition stored procedures. This can be fixed by simply providing the PartitionKeyRangeId in our RequestOptions object. The DocumentClient has logic to cache the PartitionKeyRangeIds for a collection. These same methods are used by the Bulk Executor to run cross partition stored procedures.

**Describe the solution you'd like**
Maybe expose the partition key range id cache? If you don't wanna do that then why don't you simply implement it under the hood so we can run cross partition SPs? You already did it in the bulk executor.

**Describe alternatives you've considered**
Currently the only way to access the cache and the same thing is through reflection which is nasty.

**Comment by kirillg** [comment]
Hi @Elfocrash , thank you for submitting this. Currently only system stored procedures are allowed to span across multiple partition keys. So even if we exposed pkrange_id, it would not help your scenario. We're considering opening it up, the  challenge being pkrange_id is an internal ephemeral construct and as we scale things out, what falls into a particular range changes constantly. Let's follow up on email on your exact scenario.
