### ISSUE TITLE
Remaining work estimation always return 0 and logs warnings when referencing newer versions of DocumentDB.Core

### ISSUE THREAD

**Issue by Lillskogen** [Azure/azure-cosmosdb-dotnet#627]
**Describe the bug**
Remaining work estimation always return 0 and logs warnings when referencing newer versions of DocumentDB.Core.

**To Reproduce**
In your custom project.
Reference a newer version than what is used version of Microsoft.Azure.DocmentDB.Core (verified to fail for 2.1.3).
Implement a custom feed processor that process change feeds.
In the processor host build a processor and estimator.
Call the estimator to get the estimated remaining work.

            var processor = await _builder.BuildAsync();
            var estimator = await _builder.BuildEstimatorAsync();
            await processor.StartAsync();
            var estimatedRemainingWork = await estimator.GetEstimatedRemainingWork();

**Expected behavior**
The estimated remaing work should report estimated remaining work.

**Actual behavior**
The estimated remaing work always returns 0
A log warning is output with the text: Cannot parse number '-1#705'

**Environment summary**
SDK Version: .NET Core 2.1
Windows

**Additional context**
The method ExtractLsnFromSessionToken expects a partitionkeyrange to be provided in the session. It does not appear to be there for later versions of Microsoft.Azure.DocmentDB.Core

**Comment by ealsur** [comment]
This has been fixed in Change Feed SDK 2.2.1, please to the latest version.
