### ISSUE TITLE
Are CloudTableClient and CloudTable thread-safe?

### ISSUE THREAD

**Issue by iRainbow5** [Azure/azure-cosmosdb-dotnet#629]
Hi, would anyone please kindly let me know that whether Microsoft.Azure.CosmosDB.Table.CloudTableClient and Microsoft.Azure.CosmosDB.Table.CloudTable are thread-safe or not? The NuGet versions we are using is Microsoft.Azure.CosmosDB.Table 1.1.1 and Microsoft.Azure.DocumentDB 1.22.0. Thanks a lot.

**Comment by ausfeldt** [comment]
@iRainbow5 The DocumentClient is thread safe.

**Comment by iRainbow5** [comment]
How about Microsoft.Azure.CosmosDB.Table.CloudTableClient and Microsoft.Azure.CosmosDB.Table.CloudTable? We are considering whether single instance of CloudTableClient and CloudTable can be shared across mult-threads.

**Comment by wmengmsft** [comment]
@iRainbow5, yes CloudTableClient and CloudTable are thread safe. We recommend users reusing a single instance of CloudTableClient across the app.
